/**************************************************************************/
/*  as_binding_dumper.cpp                                                 */
/**************************************************************************/
/*                         This file is part of:                          */
/*                             GODOT ENGINE                               */
/*                        https://godotengine.org                         */
/**************************************************************************/
/* Copyright (c) 2014-present Godot Engine contributors (see AUTHORS.md). */
/* Copyright (c) 2007-2014 Juan Linietsky, Ariel Manzur.                  */
/*                                                                        */
/* Permission is hereby granted, free of charge, to any person obtaining  */
/* a copy of this software and associated documentation files (the        */
/* "Software"), to deal in the Software without restriction, including    */
/* without limitation the rights to use, copy, modify, merge, publish,    */
/* distribute, sublicense, and/or sell copies of the Software, and to     */
/* permit persons to whom the Software is furnished to do so, subject to  */
/* the following conditions:                                              */
/*                                                                        */
/* The above copyright notice and this permission notice shall be         */
/* included in all copies or substantial portions of the Software.        */
/*                                                                        */
/* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,        */
/* EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF     */
/* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. */
/* IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY   */
/* CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,   */
/* TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE      */
/* SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                 */
/**************************************************************************/

#include "as_binding_dumper.h"

#include "as_binding_decl.h"

#include "core/io/dir_access.h"
#include "core/io/file_access.h"
#include "core/object/class_db.h"
#include "core/templates/hash_set.h"

namespace {

// 枚举在 AS 侧的名字与运行期注册保持一致：`<声明类>_<枚举名>`（ClassDB 给的是裸名，
// 不同类会重名，所以必须带类前缀；同时净化可能出现的 '.'）。
String _enum_as_name(const ASBindingEnum &p_enum) {
	return (String(p_enum.scope) + "_" + String(p_enum.name)).replace(".", "_");
}

bool _enum_value_fits_int32(int64_t p_value) {
	return p_value >= (int64_t)INT32_MIN && p_value <= (int64_t)INT32_MAX;
}

} // namespace

String ASBindingDumper::compute_api_version(const ASBindingPlan &p_plan) {
	// 复用 plan 的稳定序列化，保证 hash 只随 API 内容变化，不随 HashMap 遍历顺序变化。
	return p_plan.serialize_stable().sha256_text();
}

String ASBindingDumper::_render_declaration(const ASBindingPlan &p_plan) {
	// 可见类集合：与运行期一致地决定 opImplCast 链到哪一层为止。
	HashSet<StringName> classes;
	for (const ASBindingClass &c : p_plan.get_classes()) {
		classes.insert(c.name);
	}

	String out;
	out += "// angelscript-api-version: " + compute_api_version(p_plan) + "\n";
	out += "// Generated by --dump-angelscript-api. Do not edit.\n";
	out += "// Names match runtime registration exactly:\n";
	out += "//   - object types require explicit handle syntax: Node @n = Node();\n";
	out += "//   - enums are named <Scope>_<Enum>;\n";
	out += "//   - constants are named <Class>_<NAME>.\n";
	out += "\n";

	if (!p_plan.get_value_types().is_empty()) {
		out += "// ---------------- builtin value types ----------------\n";
		for (const ASBindingValueType &vt : p_plan.get_value_types()) {
			out += "class " + vt.as_name + "; // members are generated from Variant introspection\n";
		}
		out += "\n";
	}

	if (!p_plan.get_enums().is_empty()) {
		out += "// ---------------- enums ----------------\n";
		for (const ASBindingEnum &e : p_plan.get_enums()) {
			String body;
			for (const Pair<String, int64_t> &v : e.values) {
				// 运行期只注册 int32 范围内的值，这里必须同样过滤，否则 dump 与引擎不一致。
				if (!_enum_value_fits_int32(v.second)) {
					continue;
				}
				body += "\t" + v.first + " = " + itos(v.second) + ",\n";
			}
			if (body.is_empty()) {
				continue;
			}
			out += "enum " + _enum_as_name(e) + " {\n" + body + "};\n";
		}
		out += "\n";
	}

	bool has_constants = false;
	for (const ASBindingClass &c : p_plan.get_classes()) {
		if (!c.constants.is_empty()) {
			has_constants = true;
			break;
		}
	}
	if (has_constants) {
		out += "// ---------------- constants ----------------\n";
		for (const ASBindingClass &c : p_plan.get_classes()) {
			for (const ASBindingConstant &k : c.constants) {
				out += "const int64 " + String(c.name) + "_" + k.name + " = " + itos(k.value) + ";\n";
			}
		}
		out += "\n";
	}

	out += "// ---------------- object types ----------------\n";
	for (const ASBindingClass &c : p_plan.get_classes()) {
		out += "class " + String(c.name) + " { // extends: " + String(c.parent) + "\n";
		if (c.instantiable) {
			out += "\t// factory: " + String(c.name) + " @x = " + String(c.name) + "();\n";
		}
		for (const ASBindingMethod &m : c.methods) {
			out += "\t" + m.as_decl + ";\n";
		}
		for (const ASBindingProperty &p : c.properties) {
			out += "\t" + p.as_type + " get_" + p.name + "() const property;\n";
			if (!p.read_only) {
				out += "\tvoid set_" + p.name + "(" + as_binding_render_param(p.as_type) + ") property;\n";
			}
		}
		// 继承边：运行期沿父链上溯并在第一个未注册祖先处停止，dump 必须照抄同一规则。
		StringName ancestor = c.parent;
		while (!ancestor.is_empty() && classes.has(ancestor)) {
			out += "\t" + String(ancestor) + "@ opImplCast() const;\n";
			ancestor = ClassDB::get_parent_class_nocheck(ancestor);
		}
		out += "}\n\n";
	}

	return out;
}

String ASBindingDumper::_render_unbound(const ASBindingPlan &p_plan) {
	Vector<String> lines;
	for (const ASUnboundEntry &e : p_plan.get_unbound()) {
		lines.push_back(String(e.owner) + "\t" + e.member + "\t" + e.reason);
	}
	// plan 的 unbound 顺序来自 ClassDB 遍历，可能不稳定；产物必须可复现，所以排序。
	lines.sort();

	String out;
	for (const String &line : lines) {
		out += line + "\n";
	}
	return out;
}

Error ASBindingDumper::write(const ASBindingPlan &p_plan, const String &p_dir) {
	Error err = DirAccess::make_dir_recursive_absolute(p_dir);
	if (err != OK) {
		ERR_PRINT(vformat("AngelScript: cannot create dump directory '%s' (%d).", p_dir, (int)err));
		return err;
	}

	const String decl = _render_declaration(p_plan);
	const String unbound = _render_unbound(p_plan);

	{
		Ref<FileAccess> f = FileAccess::open(p_dir.path_join("angelscript_api.d.as"), FileAccess::WRITE);
		if (f.is_null()) {
			ERR_PRINT(vformat("AngelScript: cannot write '%s'.", p_dir.path_join("angelscript_api.d.as")));
			return ERR_CANT_CREATE;
		}
		f->store_string(decl);
	}
	{
		Ref<FileAccess> f = FileAccess::open(p_dir.path_join("angelscript_unbound.txt"), FileAccess::WRITE);
		if (f.is_null()) {
			ERR_PRINT(vformat("AngelScript: cannot write '%s'.", p_dir.path_join("angelscript_unbound.txt")));
			return ERR_CANT_CREATE;
		}
		f->store_string(unbound);
	}
	return OK;
}
